### ISSUE TITLE
Plugin doesn't work for UE4 4.27

### ISSUE THREAD

**Issue by Dalish21** [ScottKirvan/ScooterUtils#19]
Hi. I tried to activate this plugin for UE4 4.27, but it doesn't work. You wrote that Supported Platforms 4.25, 4.26, 4.27, 5.0, 5.1, 5.2, & 5.3. Can you check it for UE4 4.27? May be you have previous version of plugin, that worked for 4.27 and you can upload it too?

**Comment by ScottKirvan** [comment]
Make sure you've downloaded the [All-Versions-Prior-to-5.1](https://github.com/ScottKirvan/ScooterUtils/tree/All-Versions-Prior-to-5.1) branch.

**Comment by ScottKirvan** [comment]
I haven't heard back, so I'm going to take this as it being ok - thanks!
